service: serverless-stepf-api-gw
frameworkVersion: '2'

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

functions:
  handler:
    handler: functions/handler.handler

stepFunctions:
  stateMachines:
    apiGatewayTrigger:
      name: api-gateway-trigger
      events:
        - http:
            path: /
            method: POST
      definition:
        Comment: Demonstrate how API Gateway works
        StartAt: DoSomething
        States:
          DoSomething:
            Type: Task
            Resource:
              Fn::GetAtt: [handler, Arn]
            End: true
